version: "3"
services:
  news-crawler:
    build: .
    container_name: news_crawler
    restart: always
    env_file:
      - .env
    volumes:
      - ./service_account.json:/app/service_account.json:ro
